# Lista 7 - Física Computacional
Aluna: Ylana Karolina Santos Lopes

In [70]:
from numpy import array, zeros, linalg, copy, dot, arange, eye
from banded import banded


#### Problema 1: Circuito de resistores
a) Realizando o sistema (não sei fazer as matrizes no jupyter) chegamos às equações: 

$$ 4V_{1} - V_{2} - V_{3} - V_{4} = V_{+}$$
$$ -V_{1} + 3V_{2} - V_{4} = 0$$
$$ -V_{1}  + 3V_{3} - V_{4} = V_{+}$$
$$ -V_{1} + V_{2} - V_{3} - V_{4} = 0$$

In [71]:
A = array([[4,-1,-1,-1],
           [-1,3,0,-1],
           [-1,0,3,-1],
           [-1,-1,-1,4]],float)

v_p = 5 

v = array([v_p,0,v_p,0],float)
N = len(v)
x = zeros(N)


In [72]:
## b)
for i in range(N):
    print(A)
    v[i] = v[i]/A[i,i]
    A[i,:] = A[i,:]/A[i,i]
    for j in range(i+1,N):
        mult = -(A[j,i])
        A[j,:] = A[j,:] + mult*A[i,:]
        v[j] = v[j] + mult*v[i]
print(A)
print(v)

# Fase da substituição retrocedida
for i in range(N-1,-1,-1):
    x[i] = v[i]
    for j in range(i+1,N):
        x[i] -= A[i,j]*x[j]  

print("Solução: ")
print(x)

[[ 4. -1. -1. -1.]
 [-1.  3.  0. -1.]
 [-1.  0.  3. -1.]
 [-1. -1. -1.  4.]]
[[ 1.   -0.25 -0.25 -0.25]
 [ 0.    2.75 -0.25 -1.25]
 [ 0.   -0.25  2.75 -1.25]
 [ 0.   -1.25 -1.25  3.75]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          2.72727273 -1.36363636]
 [ 0.          0.         -1.36363636  3.18181818]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          1.         -0.5       ]
 [ 0.          0.          0.          2.5       ]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          1.         -0.5       ]
 [ 0.          0.          0.          1.        ]]
[1.25       0.45454545 2.33333333 2.        ]
Solução: 
[3.         1.66666667 3.33333333 2.        ]


In [73]:
## c) usando o linalg (reinicializando a matriz orginal) 

sol = linalg.solve(A, v)
print(sol)


[3.         1.66666667 3.33333333 2.        ]


#### Problema 2

In [37]:
### a)
A = array([[2, 1, 4, 1],
           [3, 4, -1, -1],
           [1, -4, 1, 5],
           [2, -2, 1, 3]],float)


v = array([-4,3,9,7],float)
N = len(v)

x = zeros(N)

a=0
b=0

vet = zeros(N)

sol = linalg.solve(A,v)
print("Solução usando linalg.solve antes de alterar a matriz: ",sol)

for i in range(N):
    for k in range(i+1,N):
        if abs(A[k,i]) > abs(A[i,i]):
            vet = copy(A[k,:])
            A[k,:]=A[i,:]
            A[i,:]=vet
            a = v[i]
            v[i]=v[k]
            v[k]=a
    v[i] = v[i]/A[i,i]
    A[i,:] = A[i,:]/A[i,i]
    for j in range(i+1,N):
        mult = -(A[j,i])
        A[j,:] = A[j,:] + mult*A[i,:]
        v[j] = v[j] + mult*v[i]

for i in range(N-1,-1,-1):
    x[i] = v[i]
    for j in range(i+1,N):
        x[i] -= A[i,j]*x[j] 
        

print("Solução: ",x)

Solução usando linalg.solve antes de alterar a matriz:  [ 2. -1. -2.  1.]
Solução:  [ 2. -1. -2.  1.]


In [39]:
B = array([[0, 1, 4, 1],
           [3, 4, -1, -1],   
           [1, -4, 1, 5],
           [2, -2, 1, 3]],float)


v2 = array([-4,3,9,7],float)
N = len(v)

y = zeros(N)

a=0
b=0

vet2 = zeros(N)

sol = linalg.solve(B,v2)
print("Solução usando linalg.solve antes de alterar a matriz: ",sol)

for i in range(N):
    for k in range(i+1,N):
        if abs(B[k,i]) > abs(B[i,i]):
            vet2 = copy(B[k,:])
            B[k,:]=B[i,:]
            B[i,:]=vet2
            b = v2[i]
            v2[i]=v2[k]
            v2[k]=b
    v2[i] = v2[i]/B[i,i]
    B[i,:] = B[i,:]/B[i,i]
    for j in range(i+1,N):
        mult2 = -(B[j,i])
        B[j,:] = B[j,:] + mult2*B[i,:]
        v2[j] = v2[j] + mult2*v2[i]

for i in range(N-1,-1,-1):
    y[i] = v2[i]
    for j in range(i+1,N):
        y[i] -= B[i,j]*y[j] 



print("Solução: ",y)

Solução usando linalg.solve antes de alterar a matriz:  [ 1.61904762 -0.42857143 -1.23809524  1.38095238]
Solução:  [ 1.61904762 -0.42857143 -1.23809524  1.38095238]


#### Problema 3: Decomposição LU

In [41]:
### a)
def lu(N, A):
    l = zeros([N,N])
    u = zeros([N,N])
    
    for i in range(N):
        for k in range(i,N):
            l[k,i]=A[k,i]
        
        v[i] = v[i]/A[i,i]
        A[i,:] = A[i,:]/A[i,i]
        
        for j in range(i+1,N):
            mult = -(A[j,i])
            A[j,:] = A[j,:] + mult*A[i,:]
            v[j] = v[j] + mult*v[i]
    u=A
    return l,u

In [46]:
A = array([[2,1,4,1],
           [3,4,-1,-1],
           [1,-4,1,5],
           [2,-2,1,3]],float)

v = array([-4,3,9,7],float)
N = len(v)


L,U=lu(N,A)
A = dot(L,U)
print("L:\n", L,"\n U:\n", U, "\n L*U = A: \n", A)

L:
 [[  2.    0.    0.    0. ]
 [  3.    2.5   0.    0. ]
 [  1.   -4.5 -13.6   0. ]
 [  2.   -3.  -11.4  -1. ]] 
 U:
 [[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]] 
 L*U = A: 
 [[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [60]:
### b) 

A = array([[2,1,4,1],
           [3,4,-1,-1],
           [1,-4,1,5],
           [2,-2,1,3]],float)

v = array([-4,3,9,7],float)

N = len(v)
x=zeros(N)
y = zeros(N)

z=linalg.solve(A,v)


L,U=lu(N,A)

for i in range(N-1,-1,-1):
    y[i] = v[i]
    for j in range(i+1,N):
        y[i] -= L[i,j]*y[j] 

        
for i in range(N-1,-1,-1):
    x[i] = y[i]
    for j in range(i+1,N):
        x[i] -= U[i,j]*x[j] 

print("Usando o Newman -> y =",y, "\nx =", x)
print("Usando solve -> x =",z)

Usando o Newman -> y = [-2.   3.6 -2.   1. ] 
x = [ 2. -1. -2.  1.]
Usando solve -> x = [ 2. -1. -2.  1.]


#### Problema 4: Uma cadeia de resistores

In [50]:
### a) Opicional

In [56]:
### b) 
V = 5
N = 6
A = eye(N)
w = array([V,V,0,0,0,0], float)

A[0][0] = 3
A[N-1][N-1] = 3
A[0][1] = -1
A[N-1][N-2] = -1

for l in range(N):
    if(l>0 and l<(N-1)):
        A[l][l] = 4
        A[l][l+1] = -1
        A[l][l-1] = -1
    if(l>=0 and l<=N-3):
        A[l][l+2] = -1
    if(l>=2):
        A[l][l-2] = -1
    
print("A: \n", A, "\n")    
    
for l in range(N):
    w[l] /= A[l][l]
    A[l][:] /= A[l][l]
    
    for k in range(l+1, N):
        mult = -A[k][l]
        A[k][:] += mult*A[l][:]
        w[k] += mult*w[l]


x= zeros(N)


for l in range(N-1,-1,-1):
    x[l] = w[l]
    for k in range(l+1,N):
        x[l] -= A[l][k]*x[k]
        

print("Voltagens:", x)

A = 
 [[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]] 

x =  [3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


In [59]:
### c)
N = 10000
A = zeros([5,N], float)

for i in range(N):
    A[0,i]=-1
    A[1,i]=-1
    A[2,i]=4
    A[3,i]=-1
    A[4,i]=-1


A[2,0]=3
A[2,N-1]=3
v=zeros(N, float)

v[0],v[1]=5,5

x = banded(A,v,2,2)

print("A: \n",A)
print("Voltagens: ", x)



A: 
 [[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [ 3.  4.  4. ...  4.  4.  3.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]
Voltagens:  [4.99888228e+00 4.99861842e+00 4.99802841e+00 ... 1.97158611e-03
 1.38158071e-03 1.11772227e-03]
